// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'1e32dc4f2fa2e2da52ed756e72a4a311a5e153e8a5beb8107081ec4f8d26076d'>;
export type ExecutionHash =
  ExecutionHashBase<'744cd5c1548cbc7758eb46cd6420c271a693ee862379785e9d249719054975b5'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Club: {
      readonly clubId: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly branch: CodecTypes['pg/text@1']['output'] | null;
      readonly website: CodecTypes['pg/text@1']['output'] | null;
      readonly facebook: CodecTypes['pg/text@1']['output'] | null;
      readonly twitter: CodecTypes['pg/text@1']['output'] | null;
      readonly instagram: CodecTypes['pg/text@1']['output'] | null;
      readonly linkedin: CodecTypes['pg/text@1']['output'] | null;
      readonly facultyInchargeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Event: {
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly eventName: CodecTypes['pg/text@1']['output'];
      readonly eventDescription: CodecTypes['pg/text@1']['output'] | null;
      readonly aicteHr: CodecTypes['pg/int4@1']['output'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly time: CodecTypes['pg/text@1']['output'] | null;
      readonly venue: CodecTypes['pg/text@1']['output'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['output'] | null;
      readonly banner: CodecTypes['pg/text@1']['output'] | null;
      readonly brochure: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Ticket: {
      readonly ticketId: CodecTypes['pg/int4@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
      readonly tnpUid: CodecTypes['pg/text@1']['output'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly time: CodecTypes['pg/text@1']['output'] | null;
      readonly venue: CodecTypes['pg/text@1']['output'] | null;
      readonly eventName: CodecTypes['pg/text@1']['output'] | null;
      readonly ticketType: CodecTypes['pg/text@1']['output'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly emailVerified: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'] | null;
      readonly username: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly googleId: CodecTypes['pg/text@1']['output'] | null;
      readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'] | null;
      readonly lastName: CodecTypes['pg/text@1']['output'] | null;
      readonly gsuiteId: CodecTypes['pg/text@1']['output'] | null;
      readonly branch: CodecTypes['pg/text@1']['output'] | null;
      readonly div: CodecTypes['pg/text@1']['output'] | null;
      readonly rollNo: CodecTypes['pg/text@1']['output'] | null;
      readonly admissionYear: CodecTypes['pg/int4@1']['output'] | null;
      readonly graduationYear: CodecTypes['pg/int4@1']['output'] | null;
      readonly tndUid: CodecTypes['pg/text@1']['output'] | null;
      readonly isExternal: CodecTypes['pg/bool@1']['output'];
      readonly isHost: CodecTypes['pg/bool@1']['output'];
      readonly memberOfClubId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Vault: {
      readonly uniqueId: CodecTypes['pg/int4@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Club: {
      readonly clubId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly branch: CodecTypes['pg/text@1']['input'] | null;
      readonly website: CodecTypes['pg/text@1']['input'] | null;
      readonly facebook: CodecTypes['pg/text@1']['input'] | null;
      readonly twitter: CodecTypes['pg/text@1']['input'] | null;
      readonly instagram: CodecTypes['pg/text@1']['input'] | null;
      readonly linkedin: CodecTypes['pg/text@1']['input'] | null;
      readonly facultyInchargeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Event: {
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly eventName: CodecTypes['pg/text@1']['input'];
      readonly eventDescription: CodecTypes['pg/text@1']['input'] | null;
      readonly aicteHr: CodecTypes['pg/int4@1']['input'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly time: CodecTypes['pg/text@1']['input'] | null;
      readonly venue: CodecTypes['pg/text@1']['input'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['input'] | null;
      readonly banner: CodecTypes['pg/text@1']['input'] | null;
      readonly brochure: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Ticket: {
      readonly ticketId: CodecTypes['pg/int4@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
      readonly tnpUid: CodecTypes['pg/text@1']['input'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly time: CodecTypes['pg/text@1']['input'] | null;
      readonly venue: CodecTypes['pg/text@1']['input'] | null;
      readonly eventName: CodecTypes['pg/text@1']['input'] | null;
      readonly ticketType: CodecTypes['pg/text@1']['input'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly emailVerified: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'] | null;
      readonly username: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly googleId: CodecTypes['pg/text@1']['input'] | null;
      readonly accessToken: CodecTypes['pg/text@1']['input'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['input'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'] | null;
      readonly lastName: CodecTypes['pg/text@1']['input'] | null;
      readonly gsuiteId: CodecTypes['pg/text@1']['input'] | null;
      readonly branch: CodecTypes['pg/text@1']['input'] | null;
      readonly div: CodecTypes['pg/text@1']['input'] | null;
      readonly rollNo: CodecTypes['pg/text@1']['input'] | null;
      readonly admissionYear: CodecTypes['pg/int4@1']['input'] | null;
      readonly graduationYear: CodecTypes['pg/int4@1']['input'] | null;
      readonly tndUid: CodecTypes['pg/text@1']['input'] | null;
      readonly isExternal: CodecTypes['pg/bool@1']['input'];
      readonly isHost: CodecTypes['pg/bool@1']['input'];
      readonly memberOfClubId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Vault: {
      readonly uniqueId: CodecTypes['pg/int4@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly club: {
      readonly branch: CodecTypes['pg/text@1']['output'] | null;
      readonly clubId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly facebook: CodecTypes['pg/text@1']['output'] | null;
      readonly facultyInchargeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly instagram: CodecTypes['pg/text@1']['output'] | null;
      readonly linkedin: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly twitter: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly website: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly event: {
      readonly aicteHr: CodecTypes['pg/int4@1']['output'] | null;
      readonly banner: CodecTypes['pg/text@1']['output'] | null;
      readonly brochure: CodecTypes['pg/text@1']['output'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly eventDescription: CodecTypes['pg/text@1']['output'] | null;
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly eventName: CodecTypes['pg/text@1']['output'];
      readonly hostId: CodecTypes['pg/int4@1']['output'] | null;
      readonly time: CodecTypes['pg/text@1']['output'] | null;
      readonly venue: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly ticket: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly eventName: CodecTypes['pg/text@1']['output'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['output'] | null;
      readonly ticketId: CodecTypes['pg/int4@1']['output'];
      readonly ticketType: CodecTypes['pg/text@1']['output'] | null;
      readonly time: CodecTypes['pg/text@1']['output'] | null;
      readonly tnpUid: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
      readonly venue: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly user: {
      readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
      readonly admissionYear: CodecTypes['pg/int4@1']['output'] | null;
      readonly branch: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly div: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly emailVerified: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly firstName: CodecTypes['pg/text@1']['output'] | null;
      readonly googleId: CodecTypes['pg/text@1']['output'] | null;
      readonly graduationYear: CodecTypes['pg/int4@1']['output'] | null;
      readonly gsuiteId: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'] | null;
      readonly isExternal: CodecTypes['pg/bool@1']['output'];
      readonly isHost: CodecTypes['pg/bool@1']['output'];
      readonly lastName: CodecTypes['pg/text@1']['output'] | null;
      readonly memberOfClubId: CodecTypes['pg/int4@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
      readonly rollNo: CodecTypes['pg/text@1']['output'] | null;
      readonly tndUid: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly vault: {
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly uniqueId: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly club: {
      readonly branch: CodecTypes['pg/text@1']['input'] | null;
      readonly clubId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly facebook: CodecTypes['pg/text@1']['input'] | null;
      readonly facultyInchargeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly instagram: CodecTypes['pg/text@1']['input'] | null;
      readonly linkedin: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly twitter: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly website: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly event: {
      readonly aicteHr: CodecTypes['pg/int4@1']['input'] | null;
      readonly banner: CodecTypes['pg/text@1']['input'] | null;
      readonly brochure: CodecTypes['pg/text@1']['input'] | null;
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly eventDescription: CodecTypes['pg/text@1']['input'] | null;
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly eventName: CodecTypes['pg/text@1']['input'];
      readonly hostId: CodecTypes['pg/int4@1']['input'] | null;
      readonly time: CodecTypes['pg/text@1']['input'] | null;
      readonly venue: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly ticket: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly eventName: CodecTypes['pg/text@1']['input'] | null;
      readonly hostId: CodecTypes['pg/int4@1']['input'] | null;
      readonly ticketId: CodecTypes['pg/int4@1']['input'];
      readonly ticketType: CodecTypes['pg/text@1']['input'] | null;
      readonly time: CodecTypes['pg/text@1']['input'] | null;
      readonly tnpUid: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
      readonly venue: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly user: {
      readonly accessToken: CodecTypes['pg/text@1']['input'] | null;
      readonly admissionYear: CodecTypes['pg/int4@1']['input'] | null;
      readonly branch: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly div: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly emailVerified: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly firstName: CodecTypes['pg/text@1']['input'] | null;
      readonly googleId: CodecTypes['pg/text@1']['input'] | null;
      readonly graduationYear: CodecTypes['pg/int4@1']['input'] | null;
      readonly gsuiteId: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'] | null;
      readonly isExternal: CodecTypes['pg/bool@1']['input'];
      readonly isHost: CodecTypes['pg/bool@1']['input'];
      readonly lastName: CodecTypes['pg/text@1']['input'] | null;
      readonly memberOfClubId: CodecTypes['pg/int4@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['input'] | null;
      readonly rollNo: CodecTypes['pg/text@1']['input'] | null;
      readonly tndUid: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly vault: {
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly uniqueId: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly club: {
              columns: {
                readonly clubId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly branch: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly website: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly facebook: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly twitter: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly instagram: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly linkedin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly facultyInchargeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['clubId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'club_facultyInchargeId_idx_6a862bb4';
                  readonly prefix: 'club_facultyInchargeId_idx';
                  readonly columns: readonly ['facultyInchargeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'club';
                    readonly columns: readonly ['facultyInchargeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly event: {
              columns: {
                readonly eventId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly eventName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly eventDescription: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly aicteHr: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly time: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly venue: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly hostId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly banner: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly brochure: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['eventId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'event_hostId_idx_05205577';
                  readonly prefix: 'event_hostId_idx';
                  readonly columns: readonly ['hostId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['hostId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'club';
                    readonly columns: readonly ['clubId'];
                  };
                },
              ];
            };
            readonly ticket: {
              columns: {
                readonly ticketId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly eventId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tnpUid: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly time: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly venue: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly eventName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly ticketType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly hostId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['ticketId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'ticket_userId_idx_a489d58a';
                  readonly prefix: 'ticket_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ticket_eventId_idx_6a266d47';
                  readonly prefix: 'ticket_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ticket_hostId_idx_05205577';
                  readonly prefix: 'ticket_hostId_idx';
                  readonly columns: readonly ['hostId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ticket';
                    readonly columns: readonly ['hostId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'club';
                    readonly columns: readonly ['clubId'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ticket';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ticket';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['eventId'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly emailVerified: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly googleId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly accessToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly refreshToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly expiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly gsuiteId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly branch: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly div: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly rollNo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly admissionYear: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly graduationYear: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tndUid: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly isExternal: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly isHost: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly memberOfClubId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['googleId'] },
                { readonly columns: readonly ['gsuiteId'] },
                { readonly columns: readonly ['tndUid'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'user_memberOfClubId_idx_506e3a3b';
                  readonly prefix: 'user_memberOfClubId_idx';
                  readonly columns: readonly ['memberOfClubId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['memberOfClubId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'club';
                    readonly columns: readonly ['clubId'];
                  };
                },
              ];
            };
            readonly vault: {
              columns: {
                readonly uniqueId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly eventId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['uniqueId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'vault_userId_idx_a489d58a';
                  readonly prefix: 'vault_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'vault_eventId_idx_6a266d47';
                  readonly prefix: 'vault_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vault';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vault';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['eventId'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
    readonly ticket: { readonly namespace: 'public' & NamespaceId; readonly model: 'Ticket' };
    readonly vault: { readonly namespace: 'public' & NamespaceId; readonly model: 'Vault' };
    readonly club: { readonly namespace: 'public' & NamespaceId; readonly model: 'Club' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Club: {
            readonly fields: {
              readonly clubId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly branch: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly website: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly facebook: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly twitter: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly instagram: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly linkedin: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly facultyInchargeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly facultyIncharge: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['facultyInchargeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly hostedEvents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['clubId'];
                  readonly targetFields: readonly ['hostId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'club';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly clubId: { readonly column: 'clubId' };
                readonly name: { readonly column: 'name' };
                readonly branch: { readonly column: 'branch' };
                readonly website: { readonly column: 'website' };
                readonly facebook: { readonly column: 'facebook' };
                readonly twitter: { readonly column: 'twitter' };
                readonly instagram: { readonly column: 'instagram' };
                readonly linkedin: { readonly column: 'linkedin' };
                readonly facultyInchargeId: { readonly column: 'facultyInchargeId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Event: {
            readonly fields: {
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventDescription: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly aicteHr: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly time: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly venue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly hostId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly banner: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly brochure: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly host: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Club' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['hostId'];
                  readonly targetFields: readonly ['clubId'];
                };
              };
              readonly tickets: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ticket';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly vaults: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Vault';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly eventId: { readonly column: 'eventId' };
                readonly eventName: { readonly column: 'eventName' };
                readonly eventDescription: { readonly column: 'eventDescription' };
                readonly aicteHr: { readonly column: 'aicteHr' };
                readonly date: { readonly column: 'date' };
                readonly time: { readonly column: 'time' };
                readonly venue: { readonly column: 'venue' };
                readonly hostId: { readonly column: 'hostId' };
                readonly banner: { readonly column: 'banner' };
                readonly brochure: { readonly column: 'brochure' };
              };
            };
          };
          readonly Ticket: {
            readonly fields: {
              readonly ticketId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tnpUid: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly time: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly venue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ticketType: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly hostId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly host: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Club' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['hostId'];
                  readonly targetFields: readonly ['clubId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ticket';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly ticketId: { readonly column: 'ticketId' };
                readonly eventId: { readonly column: 'eventId' };
                readonly userId: { readonly column: 'userId' };
                readonly tnpUid: { readonly column: 'tnpUid' };
                readonly date: { readonly column: 'date' };
                readonly time: { readonly column: 'time' };
                readonly venue: { readonly column: 'venue' };
                readonly eventName: { readonly column: 'eventName' };
                readonly ticketType: { readonly column: 'ticketType' };
                readonly hostId: { readonly column: 'hostId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly emailVerified: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly googleId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accessToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly firstName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly gsuiteId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly branch: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly div: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rollNo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly admissionYear: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly graduationYear: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tndUid: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isExternal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly isHost: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly memberOfClubId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly memberOfClub: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Club' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['memberOfClubId'];
                  readonly targetFields: readonly ['clubId'];
                };
              };
              readonly tickets: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ticket';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly vaults: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Vault';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly emailVerified: { readonly column: 'emailVerified' };
                readonly image: { readonly column: 'image' };
                readonly username: { readonly column: 'username' };
                readonly name: { readonly column: 'name' };
                readonly googleId: { readonly column: 'googleId' };
                readonly accessToken: { readonly column: 'accessToken' };
                readonly refreshToken: { readonly column: 'refreshToken' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly firstName: { readonly column: 'firstName' };
                readonly lastName: { readonly column: 'lastName' };
                readonly gsuiteId: { readonly column: 'gsuiteId' };
                readonly branch: { readonly column: 'branch' };
                readonly div: { readonly column: 'div' };
                readonly rollNo: { readonly column: 'rollNo' };
                readonly admissionYear: { readonly column: 'admissionYear' };
                readonly graduationYear: { readonly column: 'graduationYear' };
                readonly tndUid: { readonly column: 'tndUid' };
                readonly isExternal: { readonly column: 'isExternal' };
                readonly isHost: { readonly column: 'isHost' };
                readonly memberOfClubId: { readonly column: 'memberOfClubId' };
              };
            };
          };
          readonly Vault: {
            readonly fields: {
              readonly uniqueId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'vault';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uniqueId: { readonly column: 'uniqueId' };
                readonly eventId: { readonly column: 'eventId' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'club';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
